services:
  web:
    image: odoo:15.0
    container_name: calyx-odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --load-language=es_AR --language=es_AR --dev=reload
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./addons:/mnt/extra-addons:cached
      - ./odoo-data:/mnt/odoo-data:cached
      - ./config/odoo.conf:/etc/odoo/odoo.conf:cached
      - /dev/shm:/dev/shm
    user: "${UID}:${GID}"

  db:
    image: postgres:15
    container_name: calyx-odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data:cached
      - /dev/shm:/dev/shm
    ports:
      - "5432:5432"
    user: "${UID}:${GID}"